In [14]:
pip install qutip


[notice] A new release of pip is available: 23.1.2 -> 25.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [15]:
pip install matplotlib


[notice] A new release of pip is available: 23.1.2 -> 25.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [17]:
import numpy as np
from pylab import *
import matplotlib.pyplot as plt
from qutip import *
import math

In [18]:
X = sigmax() #Sigma X
Y = sigmay() #Sigma Y
Z = sigmaz() #Sigma Z

for number, (name, gate) in enumerate(zip(["X", "Y", "Z"], [X, Y, Z]), start = 1):
  print(f"{number}. Pauli-{name} Matrix: {gate} \n")

1. Pauli-X Matrix: Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0. 1.]
 [1. 0.]] 

2. Pauli-Y Matrix: Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]] 

3. Pauli-Z Matrix: Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]] 



In [19]:
# Various ways to compute matrices by each other (We are using the Pauli-X operator)
X2 = X ** 2
X3 = X * X

for variable, multiplication in zip (["X2", "X3"], [X2, X3]):
  print(f"{variable} Matrix: {multiplication}\n")

X2 Matrix: Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[1. 0.]
 [0. 1.]]

X3 Matrix: Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[1. 0.]
 [0. 1.]]



In [20]:
#Computing the X, Y, Z matrices by each other
gates_representations = [("X", X), ("Y", Y), ("Z", Z)]
number = 1

for name1, gate1 in gates_representations:
  for name2, gate2 in gates_representations:
    print(f"{number}. ({name1} x {name2}) Matrix: {gate1 * gate2}\n")
    number += 1

1. (X x X) Matrix: Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[1. 0.]
 [0. 1.]]

2. (X x Y) Matrix: Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=False
Qobj data =
[[0.+1.j 0.+0.j]
 [0.+0.j 0.-1.j]]

3. (X x Z) Matrix: Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=False
Qobj data =
[[ 0. -1.]
 [ 1.  0.]]

4. (Y x X) Matrix: Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=False
Qobj data =
[[0.-1.j 0.+0.j]
 [0.+0.j 0.+1.j]]

5. (Y x Y) Matrix: Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[1. 0.]
 [0. 1.]]

6. (Y x Z) Matrix: Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=False
Qobj data =
[[0.+0.j 0.+1.j]
 [0.+1.j 0.+0.j]]

7. (Z x X) Matrix: Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=False
Qobj data =
[[ 0.  1.]
 [-1.  0.]]

8

In [21]:
#Commutativity
C1 = commutator(X, Y, 'normal') #XY - YX
C2 = commutator(X, Y, 'anti') #XY + YX

print(f"{C1}\n")
print(f"{C2}\n")

#Horizontal Matrix
horizontal_matrix = Qobj([[0 , 1]])

#Vertical Matrix
vertical_matrix = Qobj([[0], [1]])

print(f"{horizontal_matrix}\n")
print(f"{vertical_matrix}\n")

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=False
Qobj data =
[[0.+2.j 0.+0.j]
 [0.+0.j 0.-2.j]]

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0. 0.]
 [0. 0.]]

Quantum object: dims=[[1], [2]], shape=(1, 2), type='bra', dtype=Dense
Qobj data =
[[0. 1.]]

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [1.]]



In [22]:
H = Qobj([[1/sqrt(2), 1/sqrt(2)], [1/sqrt(2), -1/sqrt(2)]]) #Hadamard Gate
print(tensor(H, H))

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.5  0.5  0.5  0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5]]


## Qu-Quarts

In [23]:
# Define single qubit basis states
qubit_0 = basis(2, 0)  # |0⟩
qubit_1 = basis(2, 1)  # |1⟩

# Create the 4 basis states of the ququart
ququart_00 = tensor(qubit_0, qubit_0)  # |00⟩
ququart_01 = tensor(qubit_0, qubit_1)  # |01⟩
ququart_10 = tensor(qubit_1, qubit_0)  # |10⟩
ququart_11 = tensor(qubit_1, qubit_1)  # |11⟩

print("Ququart basis states:\n")
for i, state in enumerate([ququart_00, ququart_01, ququart_10, ququart_11]):
    print(f"|{i:02b}⟩ = {state.dag()}")

Ququart basis states:

|00⟩ = Quantum object: dims=[[1], [2, 2]], shape=(1, 4), type='bra', dtype=Dense
Qobj data =
[[1. 0. 0. 0.]]
|01⟩ = Quantum object: dims=[[1], [2, 2]], shape=(1, 4), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0.]]
|10⟩ = Quantum object: dims=[[1], [2, 2]], shape=(1, 4), type='bra', dtype=Dense
Qobj data =
[[0. 0. 1. 0.]]
|11⟩ = Quantum object: dims=[[1], [2, 2]], shape=(1, 4), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 1.]]


In [24]:
#Making a QuQuart

quart_state1 = Qobj([[1, 0, 1, 0]]) # |bra>
quart_state2 = Qobj([[1, 1, 0, 0]]).trans() # <ket|


print(quart_state1)
print(quart_state2)

print(f"\nInner Product: {quart_state1 * quart_state2}")
print(f"\nOuter Product: {quart_state2 * quart_state1}")

Quantum object: dims=[[1], [4]], shape=(1, 4), type='bra', dtype=Dense
Qobj data =
[[1. 0. 1. 0.]]
Quantum object: dims=[[4], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [1.]
 [0.]
 [0.]]

Inner Product: (1+0j)

Outer Product: Quantum object: dims=[[4], [4]], shape=(4, 4), type='oper', dtype=CSR, isherm=False
Qobj data =
[[1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
